# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Simple-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build123:

    runs-on: windows-latest
    env:
      solutionPath: .\WinNetCoreApp

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.solutionPath }}
    - name: Build
      run: dotnet build ${{ env.solutionPath }} --no-restore
    - name: Test
      run: dotnet test ${{ env.solutionPath }} --no-build --verbosity normal
      
  deploy_server:
    runs-on: ubuntu-latest
    needs: build123
    environment: prod
    steps:
    - run: echo "deploy"
    
  deploy_clients:
    runs-on: ubuntu-latest
    needs: [build123, deploy_server]
    steps:
    - run: echo "deploy"
